apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
          name: mongo-express
        envFrom:
        - secretRef:
            name: mongo-express-secret
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: default
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
  - name: mongo-express
    protocol: "TCP"
    port: 8081
    targetPort: 8081