apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
          name: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongo.default.svc.cluster.local
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: ${MONGO_INITDB_ROOT_USERNAME}
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: ${MONGO_INITDB_ROOT_PASSWORD}
          - name: ME_CONFIG_BASICAUTH_USERNAME
            value: ${MONGO_WEB_USERNAME}
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            value: ${MONGO_WEB_PASSWORD}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: default
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081