
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
#   revisionHistoryLimit: 10
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
        containers:
        - name: redis
          image: redis:alpine
          imagePullPolicy: IfNotPresent
          command:
          - redis-server
          args: ["/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
          - name: redis-storage
            mountPath: /var/lib/redis
          - name: redis-conf
            mountPath: /etc/redis
            readOnly: true
        volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-conf
          secret:
            secretName: redis-secret

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379