apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: nginx-config
  labels:
    app: nginx-config
data:
  default.conf: |
    upstream socketio {
      server backend:3002;
    }

    upstream backend {
      server backend:3001;
    }

    upstream frontend {
      server frontend:3000;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name  _;

      location ^~ /api/login {
        proxy_pass http://backend/api/login;
      }

      location /api/wss {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://socketio/;
        proxy_connect_timeout 30m;
        proxy_send_timeout 30m;
        proxy_read_timeout 30m;

      }

      location / {
        proxy_pass http://frontend/;
      }
    }