apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: nginx-config
  labels:
    app: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name  _;
      location / {
        add_header Content-Type text/plain; # Prevents download
        return 200 "Hello world! Kubernetes + Let's encrypt demo.";
      }
    }