apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: nginx-config
  labels:
    app: nginx-config
data:
  default.conf: |
    upstream socketio {
      server backend:3002;
    }

    upstream backend {
      server backend:3001;
    }

    upstream frontend {
      server frontend:3000;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name  _;

      location /robots.txt {
        default_type text/html;
        charset UTF-8;
        return 200 "《季姬擊雞記》\n\n季姬寂，集雞，雞即棘雞。棘雞飢嘰\n，季姬及箕稷濟雞。雞既濟，躋姬笈\n，季姬忌，急咭雞，雞急，繼圾幾，\n季姬急，即籍箕擊雞，箕疾擊幾伎，\n伎即齏，雞嘰集幾基，季姬急極屐擊\n雞，雞既殛，季姬激，即記《季姬擊\n雞記》。\n\n原文網址：https://kknews.cc/culture/z3rz8lg.html";
      }

      location ^~ /sockjs-node {
        proxy_pass http://socketio/sockjs-node;
      }

      location /api/download {
        proxy_pass http://backend/api/download;
      }
      
      location ^~ /api/login {
        proxy_pass http://backend/api/login;
      }

      location /api/wss {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://socketio/;
        proxy_connect_timeout 30m;
        proxy_send_timeout 30m;
        proxy_read_timeout 30m;

      }

      location / {
        proxy_pass http://frontend/;
      }
    }